-- Hiro Coffee: 初期スキーマ（新規 Supabase プロジェクト用）
-- 本番 DB に既に存在する場合も IF NOT EXISTS で安全にスキップされます。

CREATE TABLE IF NOT EXISTS public.reservations (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text        NOT NULL,
  item        text        NOT NULL,
  time        text        NOT NULL,
  note        text        DEFAULT '',
  status      text        NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'done'))
);

CREATE INDEX IF NOT EXISTS reservations_created_at_idx
  ON public.reservations (created_at DESC);

CREATE INDEX IF NOT EXISTS reservations_status_idx
  ON public.reservations (status);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'reservations'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.reservations;
  END IF;
END $$;
